apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-secret-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: ""
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://chatwork.github.io/charts"
      path: ""
      targetRevision: 0.2.4
      chart: aws-secret-operator
      helm:
        valueFiles:
          - $values/aws-secret-operator/values.yaml
    - repoURL: https://github.com/jppol-idp/argocd-eks-001-test-config.git
      targetRevision: main
      ref: values
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
