apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: cert-manager
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: cert-manager
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://charts.jetstack.io"
      path: ""
      targetRevision: v1.15.3
      chart: cert-manager
      helm:
        valueFiles:
          - $values/cert-manager/values.yaml
    - repoURL: https://github.com/jppol-ido/argocd-eks-001-test-config.git
      targetRevision: main
      ref: values
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
