apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: external-dns
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: kube-system
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://kubernetes-sigs.github.io/external-dns"
      path: ""
      targetRevision: 1.15.0
      chart: external-dns
      helm:
        valueFiles:
          - $values/external-dns/values.yaml
    - repoURL: https://github.com/jppol-idp/argocd-eks-001-test-config.git
      targetRevision: main
      ref: values
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
