apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
  name: argocd-github-client-secret
  namespace: argocd
spec:
  metadata:
    labels:
      app.kubernetes.io/part-of: argocd
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: idp/github-oauth-apps/argocd-client-secret
      versionId: e6c5e03b-ca5d-49e4-853f-2967e5669721
