apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: grafana
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      path: ""
      targetRevision: "8.5.8"
      chart: grafana
      helm:
        valueFiles:
          - $values/grafana/values.yaml
    - repoURL: https://github.com/jppol-idp/argocd-eks-001-test-config.git
      targetRevision: main
      ref: values
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
