apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-alloy
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  destination:
    name: ""
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://grafana.github.io/helm-charts"
      path: ""
      targetRevision: 0.7.0
      chart: alloy
      helm:
        valueFiles:
          - $values/grafana-alloy/values.yaml
    - repoURL: https://github.com/jppol-idp/argocd-eks-001-test-config.git
      targetRevision: main
      ref: values
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
