apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: kubecost

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
  name: kubecost-basic-auth
  namespace: kubecost
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: idp/kubecost-basic-auth
      versionId: d5ce54d7-c559-4d4e-85aa-e337406997ef

---
apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: docker-io-helm-oci
  namespace: argocd
stringData:
  url: public.ecr.aws/kubecost/
  name: cost-analyzer
  type: helm
  enableOCI: "true"

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: kubecost
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: kubecost
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "public.ecr.aws/kubecost/cost-analyzer"
      path: ""
      targetRevision: "2.4.1"
      chart: cost-analyzer
      helm:
        valueFiles:
          - $values/kubecost/values.yaml
    - repoURL: https://github.com/Lynetk/eks-argo-config.git
      targetRevision: main
      ref: values
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
