apiVersion: v1
kind: Namespace
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "2"
  name: kubecost

---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "3"
  name: kubecost-basic-auth
  namespace: kubecost
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: idp/kubecost-basic-auth
      versionId: fc7a16de-b6e8-4eee-890c-1d4ccf84ef9f

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: kubecost
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ""
    namespace: kubecost
    server: "https://kubernetes.default.svc"
  sources:
    - repoURL: "https://kubecost.github.io/cost-analyzer"
      path: ""
      targetRevision: "2.4.1"
      chart: cost-analyzer
      helm:
        valueFiles:
          - $values/kubecost/values.yaml
    - repoURL: https://github.com/Lynetk/eks-argo-config.git
      targetRevision: main
      ref: values
  project: idp-project
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
