apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: homepage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: idp-custom
    server: https://kubernetes.default.svc
  project: idp-project
  sources:
    - repoURL: https://jameswynn.github.io/helm-charts/
      chart: homepage
      targetRevision: 2.0.1
      helm:
        valueFiles:
          - $values/homepage/values.yaml
    - repoURL: https://github.com/jppol-idp/argocd-eks-001-test-config.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
