apiVersion: v1
kind: Namespace
metadata:
  name: postgres
---
apiVersion: mumoshu.github.io/v1alpha1
kind: AWSSecret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "11"
  name: postgres
  namespace: postgres
spec:
  stringDataFrom:
    secretsManagerSecretRef:
      secretId: idp/postgres
      versionId: 1d00d8de-2bf3-43b2-92cc-f677434d74d3
