apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ai-project
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: AI Platform Project
  sourceRepos:
    - "*"
  destinations:
    - namespace: ai
      server: https://kubernetes.default.svc
  # Deny all cluster-scoped resources from being created, except for Namespace
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  roles:
    # A role which provides read-only access to all applications in the project
    - name: read-only
      description: Read-only privileges to my-project
      policies:
        - p, proj:my-project:read-only, applications, get, my-project/*, allow
      groups:
        - my-oidc-group
    # A role which provides sync privileges to only the guestbook-dev application, e.g. to provide
    # sync privileges to a CI system
    - name: ci-role
      description: Sync privileges for guestbook-dev
      policies:
        - p, proj:my-project:ci-role, applications, sync, my-project/guestbook-dev, allow
